//Tipo de dato Números
var numero1 = 5;
var numero2 = 1500;

//Tipo de dato Texto
var texto1 = "Bicicleta";
var texto2 = "Bienvenido al curso";

//Tipo de dato Booleano
var booleanoVerdadero = true;
var booleanoFalso = false;

//Tipo de dato Null
var condicion = null;

//Tipo de dato Undefined
var sinValor; 
sinValor = "Hola buenas tardes";
console.log ( sinValor );

//Tipo de dato Arreglo [Uso de corchetes]
const arregloNumeros = [ 5000, 4200, 10, 30, 15, 10000 ];
const arregloNombres = [ "Luis", "Eric", "Diego", "Ana" ]
const arregloMixto = [ 500, "Luis", 10, "Eric" ]

//Tipo de dato Objeto persona { Uso de llaves }
var persona = {
    nombre: "Diego",
    apellidoPaterno: "Pérez",
    apellidoMaterno: "Domínguez",
    edad: 15,
    lugarNacimiento: "México"
}

//Realizando un cambio en este script 